apiVersion: v1
kind: Service
metadata:
  labels:
    app: bgd
  name: bgd
  namespace: bgd
spec:
  type: NodePort
  ports:
    - port: 31443
      targetPort: 8080
      nodePort: 31443
      name: bgd
  selector:
    app: bgd
